github.com:
    users:
        jaosito1:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: jaosito1
