#!/usr/bin/env bash

if [[ -z $1 ]]; then
    echo "Please select an option (set or get)."
    exit 1
fi

case "$1" in
    "get"|"g")
        echo "Brightness set to $(brightnessctl g). (Max is $(brightnessctl m))."
        ;;
    "set"|"s")
        if [[ -z $2 ]]; then
            echo "Please enter a value."
            exit 1
        fi

        brightnessctl s $2
        echo "Setting to brightness to $2."
        exit 0
        ;;
    *) 
        echo "Enter a valid option :("
        exit 1
        ;;
esac
