#!/usr/bin/env bash

if [[ -z "$1" ]]; then
   echo "Please input a number from 1-100 or m for mute" 
   exit 1
fi

volume_level="$1"

sink=$(pactl list short sinks | awk '/RUNNING/{print $1;exit} ')
if [[ -z "$sink" ]]; then
    sink=$( pactl list short sinks | awk '/SUSPENDED/{print $1;exit} /IDLE/{print $1;exit}' )
fi

if [[ "$volume_level" = "m" ]]; then
    pactl set-sink-mute $sink toggle 
    echo "(Un)Muted sink $sink."
    exit 0
fi

pactl set-sink-volume $sink $volume_level%
echo "Changed volume to $volume_level% for sink $sink."
