#!/usr/bin/env bash

read -r device status <<< $(nmcli device | awk '$2 == "wifi" {print $1, $3}')

if [[ -z $device || -z $status ]]; then
    echo "no wifi device found, please check nmcli"
    exit 1
fi

case "$status" in
    "disconnected") 
        nmcli device connect $device
    ;;
    "connected")
        nmcli device disconnect $device
    ;;
    *) 
        echo "something went wrong, please check nmcli"
        exit 1
    ;;
esac
