#!/bin/sh

export PATH=/home/jos/.local/bin:$PATH

# default programs
export EDITOR="nvim"
export BROWSER="firefox"

# xdg vars
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# moving files out of ~/
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

export GNUPGHOME="$XDG_DATA_HOME/gnupg"
